# Meta
title: Eluseum Framework
author: pojntfx
email: felix@pojtinger.com
description: >-
  A dead simple, minimal CSS framework.

# Config
baseurl: ""
url: "https://eluseum.tk/"
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-admin
jekyll_admin:
  hidden_links:
    - datafiles # We do not have any data files currently